In [1]:
import numpy as np 
import pandas as pd

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies = movies.merge(credits, on='title')

In [8]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.dropna(inplace=True)

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
#[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
# ["Action", "Adventure", "Fantasy", "Science Fiction"]

In [15]:
import ast

In [16]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [17]:
movies['genres'] = movies['genres'].apply(convert)

In [18]:
movies['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4806, dtype: object

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [22]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [24]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [25]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [26]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [28]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "_") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "_") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "_") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "_") for i in x])

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science_Fiction]","[culture_clash, future, space_war, space_colon...","[Sam_Worthington, Zoe_Saldana, Sigourney_Weave...",[James_Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug_abuse, exotic_island, east_india_...","[Johnny_Depp, Orlando_Bloom, Keira_Knightley, ...",[Gore_Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based_on_novel, secret_agent, sequel, mi...","[Daniel_Craig, Christoph_Waltz, Léa_Seydoux, R...",[Sam_Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc_comics, crime_fighter, terrorist, secret_i...","[Christian_Bale, Michael_Caine, Gary_Oldman, A...",[Christopher_Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science_Fiction]","[based_on_novel, mars, medallion, space_travel...","[Taylor_Kitsch, Lynn_Collins, Samantha_Morton,...",[Andrew_Stanton]

In [30]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
new_df = movies[['movie_id', 'title', 'tags']]

In [32]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\deepa\AppData\Local\Temp\ipykernel_2704\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [34]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science_Fiction culture_clash future space_war space_colony society space_travel futuristic romance space alien tribe alien_planet cgi marine soldier battle love_affair anti_war power_relations mind_and_soul 3d Sam_Worthington Zoe_Saldana Sigourney_Weaver Stephen_Lang Michelle_Rodriguez Giovanni_Ribisi Joel_David_Moore CCH_Pounder Wes_Studi Laz_Alonso Dileep_Rao Matt_Gerald Sean_Anthony_Moran Jason_Whyte Scott_Lawrence Kelly_Kilgour James_Patrick_Pitt Sean_Patrick_Murphy Peter_Dillon Kevin_Dorman Kelson_Henderson David_Van_Horn Jacob_Tomuri Michael_Blain-Rozgay Jon_Curry Luke_Hawker Woody_Schultz Peter_Mensah Sonia_Yee Jahnel_Curfman Ilram_Choi Kyla_Warren Lisa_Roumain Debra_Wilson Chris_Mala Taylor_Kibby Jodie_Landau Julie_Lamm Cullen_B._Madden Joseph_Brady_Madden Frankie_Torres Austin_Wilson Sara_Wilson Tamica_Washington-Miller Lucy_Briant Nathan_Meister Gerry_Blair Matthew_Chamberlain Paul_Yates Wray_Wilson James_Gaylyn Melvin_Leno_Clark_III Carvon_Futrell Brandon_Jelkes Micah_Moch Hanniyah_Muhammad Christopher_Nolen Christa_Oliver April_Marie_Thomas Bravita_A._Threatt Colin_Bleasdale Mike_Bodnar Matt_Clayton Nicole_Dionne Jamie_Harrison Allan_Henry Anthony_Ingruber Ashley_Jeffery Dean_Knowsley Joseph_Mika-Hunt Terry_Notary Kai_Pantano Logan_Pithyou Stuart_Pollock Raja Gareth_Ruck Rhian_Sheehan T._J._Storm Jodie_Taylor Alicia_Vela-Bailey Richard_Whiteside Nikie_Zambo Julene_Renee James_Cameron'

In [35]:
import nltk

In [36]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [37]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [38]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\deepa\AppData\Local\Temp\ipykernel_2704\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [39]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi science_fict culture_clash futur space_war space_coloni societi space_travel futurist romanc space alien tribe alien_planet cgi marin soldier battl love_affair anti_war power_rel mind_and_soul 3d sam_worthington zoe_saldana sigourney_weav stephen_lang michelle_rodriguez giovanni_ribisi joel_david_moor cch_pounder wes_studi laz_alonso dileep_rao matt_gerald sean_anthony_moran jason_whyt scott_lawr kelly_kilgour james_patrick_pitt sean_patrick_murphi peter_dillon kevin_dorman kelson_henderson david_van_horn jacob_tomuri michael_blain-rozgay jon_curri luke_hawk woody_schultz peter_mensah sonia_ye jahnel_curfman ilram_choi kyla_warren lisa_roumain debra_wilson chris_mala taylor_kibbi jodie_landau julie_lamm cullen_b._madden joseph_brady_madden frankie_torr austin_wilson sara_wilson tamica_washington-mil lucy_bri nathan_meist gerry_blair matthew_chamberlain paul_yat wray_wilson james_gaylyn melvin_leno_clark_iii carvon_futrel brandon_jelk micah_moch hanniyah_muhammad christopher_nolen christa_oliv april_marie_thoma bravita_a._threatt colin_bleasdal mike_bodnar matt_clayton nicole_dionn jamie_harrison allan_henri anthony_ingrub ashley_jefferi dean_knowsley joseph_mika-hunt terry_notari kai_pantano logan_pithy stuart_pollock raja gareth_ruck rhian_sheehan t._j._storm jodie_taylor alicia_vela-bailey richard_whitesid nikie_zambo julene_rene james_cameron'

In [40]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\deepa\AppData\Local\Temp\ipykernel_2704\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [41]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [43]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [44]:
vectors.shape

(4806, 5000)

In [45]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
cv.get_feature_names()

C:\Users\deepa\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1910',
 '1930',
 '1940',
 '1950',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1990',
 '19th',
 '19th_centuri',
 '20',
 '200',
 '20th',
 '24',
 '25',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '70',
 '_anderson',
 '_armi',
 '_armstrong',
 '_b',
 '_barri',
 '_brown',
 '_bush',
 '_cathey',
 '_d',
 '_daili',
 '_davi',
 '_dutton',
 '_earl_brown',
 '_emmet_walsh',
 '_evermor',
 '_fox',
 '_g',
 '_gainey',
 '_gary_gray',
 '_gr',
 '_griffin',
 '_hal',
 '_henson',
 '_j',
 '_jackson',
 '_john',
 '_johnson',
 '_jon',
 '_jone',
 '_jr',
 '_k',
 '_le',
 '_lee_ermey',
 '_maci',
 '_martin',
 '_mcginley',
 '_mil',
 '_miller',
 '_murphi',
 '_murray_abraham',
 '_nascarella',
 '_nelson',
 '_nichol',
 '_night_shyamalan',
 '_o',
 '_reilli',
 '_robert',
 '_roger_mitchel',
 '_romero',
 '_russel',
 '_sand',
 '_scott',
 '_simmon',
 '_smith',
 '_t',
 '_taylor',
 '_thoma',
 '_thompson',
 '_v',
 '_walsh',
 '_whit',
 '_william',
 '_wilson',
 '_young',
 'aaron',
 'aaron_eckhart',
 'aaron_taylor',
 'aasif_mandvi',
 'abandon',
 'abduct',
 'abigail_breslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abraham_benrubi',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adam_brodi',
 'adam_goldberg',
 'adam_lefevr',
 'adam_sandl',
 'adam_scott',
 'adam_shankman',
 'adapt',
 'add',
 'addict',
 'adewale_akinnuoye',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrian_martinez',
 'adrien_brodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'agbaj',
 'age',
 'age_differ',
 'agency',
 'agenda',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidan_quinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airport',
 'al',
 'al_leong',
 'al_pacino',
 'alabama',
 'alan_alda',
 'alan_arkin',
 'alan_cum',
 'alan_rickman',
 'alan_tudyk',
 'alaska',
 'albert',
 'albert_brook',
 'albert_finney',
 'alcohol',
 'alec_baldwin',
 'alec_guin',
 'alessandro_nivola',
 'alex',
 'alex_borstein',
 'alexa_penavega',
 'alexander_siddig',
 'alexis_bledel',
 'alfre_woodard',
 'alfred_hitchcock',
 'alfred_molina',
 'ali',
 'ali_lart',
 'alia_shawkat',
 'alic',
 'alice',
 'alice_braga',
 'alice_drummond',
 'alicia_silverston',
 'alicia_witt',
 'alien',
 'alien_invas',
 'alien_life',
 'alison_lohman',
 'alison_pil',
 'aliv',
 'alive',
 'allan_cordun',
 'allen',
 'allen_covert',
 'alli',
 'allianc',
 'allison_janney',
 'allow',
 'alon',
 'alongsid',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amanda_peet',
 'amanda_seyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amber_heard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'american_footbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amus',
 'amy_adam',
 'amy_poehl',
 'amy_ryan',
 'amy_sedari',
 'amy_smart',
 'ana_gastey',
 'analyst',
 'anarchic_comedi',
 'ancient',
 'anderson',
 'andi',
 'andie_macdowel',
 'andre_braugh',
 'andrea_martin',
 'andrew',
 'andrew_dali',
 'andrew_stanton',
 'android',
 'andy_dick',
 'andy_garcía',
 'andy_richt',
 'andy_samberg',
 'andy_serki',
 'angel',
 'angela_bassett',
 'angeles',
 'angelina_joli',
 'angelo',
 'anger',
 'angri',
 'angus_macinn',
 'ani',
 'anim',
 'animal_attack',
 'animal_horror',
 'animals',
 'anjelica_huston',
 'ann',
 'ann_dowd',
 'anna',
 'anna_fari',
 'anna_kendrick',
 'anna_levin',
 'anna_paquin',
 'annasophia_robb',
 'anne',
 'anne_bancroft',
 'anne_fletch',
 'anne_hathaway',
 'anne_hech',
 'anne_moss',
 'annette_ben',
 'anni',
 'annika_perga',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthony_anderson',
 'anthony_hopkin',
 'anthony_macki',
 'anthropomorph',
 'anti',
 'anti_hero',
 'anton_yelchin',
 'antoni_coron',
 'antonio_bandera',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'arci',
 'arctic',
 'area',
 'arena',
 'argument',
 'ari_graynor',
 'ariel_wint',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armin_mueller',
 'arms_deal',
 'army',
 'arnold',
 'arnold_schwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'art',
 'arthur',
 'arthur_j',
 'arthur_tovey',
 'artificial_intellig',
 'artist',
 'ash',
 'ashley',
 'ashley_judd',
 'ashton_kutch',
 'asia',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomic_bomb',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunjanue_elli',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'ava_acr',
 'aveng',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awri',
 'awry',
 'aziz_ansari',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'bahama',
 'bai_l',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'band',
 'banish',
 'bank',
 'bank_robberi',
 'banker',
 'baptist',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'barri',
 'barry_levinson',
 'barry_pepp',
 'barry_shabaka_henley',
 'bas',
 'base',
 'basebal',
 'based_on_comic_book',
 'based_on_novel',
 'based_on_play',
 'based_on_stage_mus',
 'based_on_true_ev',
 'based_on_true_stori',
 'based_on_tv_seri',
 'based_on_video_gam',
 'based_on_young_adult_novel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautiful_woman',
 'beauty',
 'becam',
 'becaus',
 'becca_sweitz',
 'becom',
 'becoming_an_adult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'behavior',
 'belief',
 'believ',
 'bell',
 'belong',
 'belov',
 'ben',
 'ben_affleck',
 'ben_chaplin',
 'ben_fost',
 'ben_gazzara',
 'ben_kingsley',
 'ben_mendelsohn',
 'ben_stil',
 'ben_whishaw',
 'bend',
 'benedict_cumberbatch',
 'benicio_del_toro',
 'benjamin',
 'benjamin_bratt',
 'bennett',
 'bent',
 'berlin',
 'bernard_hil',
 'bernard_le',
 'bernie_mac',
 'best',
 'best_friend',
 'bet',
 'beth',
 'beth_grant',
 'betray',
 'bette_midl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'bill_camp',
 'bill_cobb',
 'bill_duk',
 'bill_had',
 'bill_moseley',
 'bill_murray',
 'bill_nighi',
 'bill_nunn',
 'bill_paxton',
 'bill_pullman',
 'billi',
 'billionair',
 'billy_bob_thornton',
 'billy_burk',
 'billy_connolli',
 'billy_crudup',
 'billy_cryst',
 'billy_dee_william',
 'billy_slaught',
 'billy_west',
 'billy_zan',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'black_peopl',
 'blackmail',
 'blade',
 'blake_clark',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'blood_splatt',
 'bloodi',
 'bloodthirsti',
 'blow',
 'blue',
 'blythe_dann',
 'board',
 'boat',
 'bob',
 'bob_balaban',
 'bob_bergen',
 'bob_clendenin',
 'bob_gunton',
 'bob_hoskin',
 'bob_odenkirk',
 'bob_stephenson',
 'bobbi',
 'bobby_cannaval',
 'bobby_farrelli',
 'bodi',
 'body',
 'bodyguard',
 'bokeem_woodbin',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonnie_hunt',
 'book',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'bounti',
 'bounty_hunt',
 'box',
 'boxer',
 'boy',
 'boyd_bank',
 'boyd_holbrook',
 'boyfriend',
 'boys',
 'brad_dourif',
 'brad_garrett',
 'brad_pitt',
 'brad_william_henk',
 'bradley_coop',
 'bradley_whitford',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breckin_mey',
 'breed',
 'brendan_fras',
 'brendan_gleeson',
 'brendan_sexton_iii',
 'brent_brisco',
 'brent_spin',
 'brett_cullen',
 'brett_ratn',
 'brett_ric',
 'brian',
 'brian_cox',
 'brian_de_palma',
 'brian_dennehi',
 'brian_doyle',
 'brian_j',
 'brian_o',
 'brian_steel',
 'bride',
 'bridg',
 'bridgette_wilson',
 'brie_larson',
 'brief',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'british_secret_servic',
 'brittany_murphi',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brothel',
 'brother',
 'brother_brother_relationship',
 'brother_sister_relationship',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'bruce_campbel',
 'bruce_dern',
 'bruce_greenwood',
 'bruce_mcgil',
 'bruce_sp',
 'bruce_willi',
 'brutal',
 'bryan',
 'bryan_cranston',
 'bryan_sing',
 'bryce_dallas_howard',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddy_comedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'burglar',
 'buri',
 'burn',
 'burt_reynold',
 'busi',
 'business',
 'businessman',
 'bust',
 'butler',
 'buy',
 'byrn',
 'cabin',
 'cage',
 'cairo',
 'cal',
 'california',
 'callum_keith_renni',
 'calvin',
 'cam_gigandet',
 'came',
 'camera',
 'cameron',
 'cameron_bright',
 'cameron_diaz',
 'camp',
 'campaign',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'cannib',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'car_accid',
 'car_chas',
 'car_crash',
 'car_journey',
 'car_rac',
 'cara_seymour',
 'card',
 'care',
 'career',
 'carey_mulligan',
 'caribbean',
 'carl',
 'carla_gallo',
 'carla_gugino',
 'carlos_alazraqui',
 'carmen',
 'carmen_electra',
 'carol',
 'carol_kan',
 'caroline_aaron',
 'caroline_goodal',
 'carri',
 'carrie',
 'carrie_fish',
 'cartel',
 'carter',
 'cary',
 'cary_elw',
 'case',
 'casey_affleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cate_blanchett',
 'catherine_keen',
 'catherine_o',
 'catherine_zeta',
 'cathol',
 'catholic',
 'caught',
 'caus',
 'cave',
 'cedric_the_entertain',
 'celebr',
 'celia_imri',
 'celia_weston',
 'cell_phon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chad_michael_murray',
 'chain',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chance_kelli',
 'chang',
 'channing_tatum',
 'chao',
 'chaos',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charles_d',
 'charles_durn',
 'charles_napi',
 'charles_s',
 'charli',
 'charlie',
 'charlie_sheen',
 'charlize_theron',
 'charlotte_rampl',
 'charlton_heston',
 'charm',
 'chase',
 'chazz_palminteri',
 'cheat',
 'check',
 'cheech_marin',
 'cheerlead',
 'chef',
 'chelcie_ross',
 'chemic',
 'cher',
 'cherry_jon',
 'chevy_chas',
 'chi_mcbrid',
 'chicago',
 'chicken',
 'chief',
 'child',
 'child_abus',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chiwetel_ejiofor',
 'chloë_grace_moretz',
 'chloë_sevigni',
 'choic',
 'choos',
 'chosen',
 'chow_yun',
 'chri',
 'chris_brown',
 'chris_columbu',
 'chris_coop',
 'chris_elli',
 'chris_evan',
 'chris_hemsworth',
 'chris_klein',
 'chris_messina',
 'chris_mil',
 'chris_o',
 'chris_parnel',
 'chris_penn',
 'chris_pin',
 'chris_pratt',
 'chris_rock',
 'christ',
 'christian',
 'christian_bal',
 'christian_slat',
 'christina_appleg',
 'christina_ricci',
 'christine_baranski',
 'christma',
 'christmas',
 'christmas_parti',
 'christoph',
 'christoph_waltz',
 'christopher_fairbank',
 'christopher_guest',
 'christopher_lambert',
 'christopher_le',
 'christopher_lloyd',
 'christopher_mcdonald',
 'christopher_meloni',
 'christopher_mintz',
 'christopher_plumm',
 'christopher_walken',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciarán_hind',
 'cillian_murphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civil_war',
 'civilian',
 'claim',
 'clair',
 'claire_dan',
 'claire_forlani',
 'clan',
 'clancy_brown',
 'clark',
 'clark_gregg',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claude_van_damm',
 'clea_duval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliff_curti',
 'clifton_collins_jr',
 'climat',
 'climb',
 'clint_eastwood',
 'clint_howard',
 'clive_owen',
 'clock',
 'clone',
 'cloris_leachman',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'coach',
 'coast',
 'cocain',
 'code',
 'cody_cameron',
 'cohen',
 'col',
 'cold',
 'cold_war',
 'cole',
 'cole_haus',
 'colin_farrel',
 'colin_firth',
 'colin_hank',
 'colin_salmon',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleen_camp',
 'colleg',
 'college',
 'collid',
 'collis',
 'colm_feor',
 'colm_meaney',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'coming_of_ag',
 'coming_out',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 ...]

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
similarity = cosine_similarity(vectors)

In [50]:
similarity

array([[1.        , 0.06752237, 0.07824608, ..., 0.04454354, 0.        ,
        0.        ],
       [0.06752237, 1.        , 0.07396705, ..., 0.0210538 , 0.        ,
        0.02278028],
       [0.07824608, 0.07396705, 1.        , ..., 0.0243975 , 0.        ,
        0.        ],
       ...,
       [0.04454354, 0.0210538 , 0.0243975 , ..., 1.        , 0.04351941,
        0.04508348],
       [0.        , 0.        , 0.        , ..., 0.04351941, 1.        ,
        0.09417632],
       [0.        , 0.02278028, 0.        , ..., 0.04508348, 0.09417632,
        1.        ]])

In [51]:
similarity.shape

(4806, 4806)

In [52]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in movie_list:
        # print(i[0])
        print(new_df.iloc[i[0]].title)

In [53]:
recommend("Iron Man")

Iron Man 2
Iron Man 3
The Avengers
Avengers: Age of Ultron
Thor

In [54]:
import pickle

In [55]:
pickle.dump(new_df, open('movies.pkl','wb'))

In [56]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [57]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [58]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))